In [1]:
import pandas as pd
import urllib
import json
import csv

In [2]:
poi_reviews=pd.read_csv("C:\\Users\\dhane\\Documents\\NLP Project\\Data\\rome-poi.csv")
acc_reviews=pd.read_csv("C:\\Users\\dhane\\Documents\\NLP Project\\Data\\barcelona-accommodation.csv")
res_reviews=pd.read_csv("C:\\Users\\dhane\\Documents\\NLP Project\\Data\\paris-restaurant.csv")
attr_reviews=pd.read_csv("C:\\Users\\dhane\\Documents\\NLP Project\\Data\\amsterdam-attraction.csv",error_bad_lines=False)

In [3]:
review_links=pd.concat([poi_reviews,acc_reviews,res_reviews,attr_reviews])

In [4]:
review_links.info()
review_links=review_links.dropna()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48370 entries, 0 to 3184
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   address      45275 non-null  object
 1   category     48370 non-null  object
 2   id           48342 non-null  object
 3   lat          48370 non-null  object
 4   lng          48370 non-null  object
 5   location     48370 non-null  object
 6   name         48370 non-null  object
 7   originalId   48370 non-null  object
 8   polarity     48370 non-null  object
 9   subCategory  6887 non-null   object
 10  details      6887 non-null   object
 11  reviews      6887 non-null   object
dtypes: object(12)
memory usage: 4.8+ MB

In [5]:
review_links=review_links['reviews'].tolist()

In [7]:
import requests
count = 0
data_file = open('data_file.csv', 'w', encoding="utf-8") 
csv_writer = csv.writer(data_file) 
for i,url in enumerate(review_links):
    r = requests.get(url)   
    for rev in r.json(): 
        if count == 0:   
            # Writing headers of CSV file 
            header = rev.keys() 
            csv_writer.writerow(header) 
            count += 1  
        # Writing data of CSV file 
        csv_writer.writerow(rev.values())   
data_file.close()

In [6]:
data=pd.read_csv("data_file.csv")

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10477 entries, 0 to 10476
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   language    10477 non-null  object
 1   polarity    10477 non-null  int64
 2   rating      10477 non-null  int64
 3   source      10477 non-null  object
 4   text        10477 non-null  object
 5   time        10477 non-null  object
 6   wordsCount  10477 non-null  int64
 7   details     10477 non-null  object
dtypes: int64(3), object(5)
memory usage: 654.9+ KB

In [8]:
data=data.dropna()
data=data[data['language']=='en']

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4253 entries, 0 to 10472
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   language    4253 non-null   object
 1   polarity    4253 non-null   int64
 2   rating      4253 non-null   int64
 3   source      4253 non-null   object
 4   text        4253 non-null   object
 5   time        4253 non-null   object
 6   wordsCount  4253 non-null   int64
 7   details     4253 non-null   object
dtypes: int64(3), object(5)
memory usage: 299.0+ KB

In [10]:
data.head()

,language,polarity,rating,source,text,time,wordsCount,details
0,en,0,0,Foursquare,Turn up for changing of the guards,2010-07-27,7,http://tour-pedia.org/api/getReviewDetails?id=...
5,en,5,0,Foursquare,At the palace attending a concert!,2011-11-06,6,http://tour-pedia.org/api/getReviewDetails?id=...
8,en,10,0,Foursquare,In March every Sunday @11.50 there's a free co...,2012-03-04,18,http://tour-pedia.org/api/getReviewDetails?id=...
10,en,5,0,Foursquare,"Watch out for cars, Vespas!",2012-07-13,5,http://tour-pedia.org/api/getReviewDetails?id=...
11,en,5,0,Foursquare,It is the house of the President of the Italia...,2012-10-09,11,http://tour-pedia.org/api/getReviewDetails?id=...

In [11]:
data.tail()

,language,polarity,rating,source,text,time,wordsCount,details
10466,en,10,0,Foursquare,One of the loveliest little hidden squares in ...,2011-10-16,15,http://tour-pedia.org/api/getReviewDetails?id=...
10467,en,10,0,Foursquare,"Please visit the grave of Hendrick de Keyser, ...",2011-01-19,26,http://tour-pedia.org/api/getReviewDetails?id=...
10468,en,10,0,Foursquare,"Very nice location for exhibitions, business w...",2010-09-24,10,http://tour-pedia.org/api/getReviewDetails?id=...
10470,en,5,0,Foursquare,#Earthcoffee available,2011-11-01,2,http://tour-pedia.org/api/getReviewDetails?id=...
10472,en,10,0,Foursquare,Best place in town to watch people :),2011-09-15,7,http://tour-pedia.org/api/getReviewDetails?id=...

In [12]:
data.reset_index()

,index,language,polarity,rating,source,text,time,wordsCount,details
0,0,en,0,0,Foursquare,Turn up for changing of the guards,2010-07-27,7,http://tour-pedia.org/api/getReviewDetails?id=...
1,5,en,5,0,Foursquare,At the palace attending a concert!,2011-11-06,6,http://tour-pedia.org/api/getReviewDetails?id=...
2,8,en,10,0,Foursquare,In March every Sunday @11.50 there's a free co...,2012-03-04,18,http://tour-pedia.org/api/getReviewDetails?id=...
3,10,en,5,0,Foursquare,"Watch out for cars, Vespas!",2012-07-13,5,http://tour-pedia.org/api/getReviewDetails?id=...
4,11,en,5,0,Foursquare,It is the house of the President of the Italia...,2012-10-09,11,http://tour-pedia.org/api/getReviewDetails?id=...
...,...,...,...,...,...,...,...,...,...
4248,10466,en,10,0,Foursquare,One of the loveliest little hidden squares in ...,2011-10-16,15,http://tour-pedia.org/api/getReviewDetails?id=...
4249,10467,en,10,0,Foursquare,"Please visit the grave of Hendrick de Keyser, ...",2011-01-19,26,http://tour-pedia.org/api/getReviewDetails?id=...
4250,10468,en,10,0,Foursquare,"Very nice location for exhibitions, business w...",2010-09-24,10,http://tour-pedia.org/api/getReviewDetails?id=...
4251,10470,en,5,0,Foursquare,#Earthcoffee available,2011-11-01,2,http://tour-pedia.org/api/getReviewDetails?id=...
4252,10472,en,10,0,Foursquare,Best place in town to watch people :),2011-09-15,7,http://tour-pedia.org/api/getReviewDetails?id=...

In [13]:
data=data[['polarity','text']]

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4253 entries, 0 to 10472
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   polarity  4253 non-null   int64
 1   text      4253 non-null   object
dtypes: int64(1), object(1)
memory usage: 99.7+ KB

In [15]:
from sklearn.preprocessing import MinMaxScaler
data[['polarity']]=MinMaxScaler().fit_transform(data[['polarity']])

In [16]:
data.loc[data['polarity'] > 0.5, 'polarity'] = 1
data.loc[data['polarity'] < 0.5, 'polarity'] = 0
data.head(10)

    polarity                                               text
0        0.0                 Turn up for changing of the guards
5        0.5                 At the palace attending a concert!
8        1.0  In March every Sunday @11.50 there's a free co...
10       0.5                        Watch out for cars, Vespas!
11       0.5  It is the house of the President of the Italia...
14       0.5  Rooms open to visitation only Sunday morning. ...
20       0.5  The palace has housed thirty popes, four kings...
23       0.5  No reserved parking available -Pedestrian rout...
24       1.0  The place where your wishes can come true. Bel...
25       0.5  Many believe that these holy stairs was the sa...

In [17]:
data.to_csv("normalised_english_reviews.csv")